version: "3.3"

services:
  db:
    image: postgres:12.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  app:
    image: bazulenkov/primorsk_app:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  web:
    image: bazulenkov/primorsk_web:latest
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:
  